    
     function sample()
       {
var x=document.getElementById("t1").value;
var y=document.getElementById("t2").value;
document.getElementById("para1").innerHTML="Your name is "+x
document.getElementById("para2").innerHTML="Your address is "+y
//   alert("hi     "+x +"     You are from "+y)        
           
}
//        function sample1()
//       {
//   alert("hi i am sample 1 ")        
//           
//}
       
    